### ISSUE TITLE
What is the equivalent of gtag('consent', 'update', {'ad_storage': 'granted'}

### ISSUE THREAD

**Issue by jkohlin** [alinemorelli/react-gtm#103]
If I want to perform the following `gtag('consent', 'update', {'ad_storage': 'granted'}` GTM preview will list Consent like this:
<img width="645" alt="image" src="https://user-images.githubusercontent.com/4112881/164456171-d7f7e470-84eb-4dc8-ad9e-c3362bda69c1.png">

What is the equivalent using `TagManager.dataLayer()` ?
Or perhaps I should use another method?

**Comment by NEDDL** [comment]
I am looking for the same thing, were you able to find a solution for consent management?

**Comment by NEDDL** [comment]
@jkohlin I am looking for the same thing, were you able to find a solution for consent management?

**Comment by jkohlin** [comment]
Yes, sorry. Forgot about this question. 
This works: 
`TagManager.dataLayer({dataLayer: ['consent', 'update', { ad_storage: 'granted' }]})`

**Comment by dopry** [comment]
@jkohlin does it though? when I use tag assistant to inspect, I don't see consent events being fired by just passing an array. An array is not equivalent to an arguments object passed into the data layer by the gtm examples. I needed to implement a helper to make this work for me. 

gtag.ts
```
import TagManager from "react-gtm-module";

export function gtag(...args: any[]) {
  TagManager.dataLayer({ dataLayer: arguments });
}
```

**Comment by jkohlin** [comment]
@dopry I don't remember how we set this up in tag manager and I don't have access to it anymore but this worked in our case anyway.

**Comment by joaomelorodrigues** [comment]
Just passing by to understand if someone still recommends this solution?
