### ISSUE TITLE
We are getting "datalayer is not defined " 

### ISSUE THREAD

**Issue by akash9067** [alinemorelli/react-gtm#107]
We are using latest 2.0.11 version of React-GTM-Module in our project with next JS but we are getting **datalayer is not defined**

![17158e7d-021f-492c-a7e5-f82474670f65](https://user-images.githubusercontent.com/36261274/186853720-145bcd5d-ea0b-49da-9a48-466a1b79eaf5.jpg)

as we try to compare repo script and GTM script there were some changes i think if there were any update please update the lib.

**Comment by kodiekenta** [comment]
what version is your npm?

**Comment by tjmac21** [comment]
check your code. I'm fairly certain it should be `dataLayer`

**Comment by akash9067** [comment]
Thanks for update guys it's resolved automatically.
I am closing this issue.

**Comment by akash9067** [comment]
It resolved by default.
