### ISSUE TITLE
Guide to send custom event to GA4 with GTM

### ISSUE THREAD

**Issue by PeterWorakarn** [alinemorelli/react-gtm#108]
I have a really bad time about how to send custom event to GA4 with GTM, so I will share to your guys.

```
TagManager.dataLayer({
    dataLayer: {
      event: 'print',
      position: 'floating action button',
    }
  })
```
After you have this code to send dataLayer to GTM but GA4 will not recognize it until you register it with tag.

so you need to register new trigger as a custom dataLayer event
![image](https://user-images.githubusercontent.com/57410426/187352582-27453b98-ef56-40e0-8c2e-b2ed2715b5bc.png)

but you cannot send payload with it until you register dataLayer variable to reference it 
![image](https://user-images.githubusercontent.com/57410426/187352711-a0eba63a-8629-4713-a320-d5b55366df20.png)

after that you can pass payload as a event parameter
![image](https://user-images.githubusercontent.com/57410426/187352800-7b9c7acd-4690-4144-964e-1d9fc1eecb11.png)

credit: https://hume.dev/articles/custom-event-tracking-ga4/

**Comment by robertopuentesdiaz** [comment]
Hi @PeterWorakarn 
Today (Sep/2022), is possible use GA4 with react-gtm-module ???
