### ISSUE TITLE
Is there a react-gtm project that is still supported? This seems to have been abandoned

### ISSUE THREAD

**Issue by wlannistamps** [alinemorelli/react-gtm#119]
I saw that there are a few people who are forking this project and that issues and PRs haven't been touched in years. Can someone point me to a fork somewhere that is being actively maintained by multiple active contributors?

**Comment by macojaune** [comment]
I've found this one https://github.com/elgorditosalsero/react-gtm-hook/ I think i'll give it a try right now. 
Started with react-gtm but it's acting weird and there is not much help here.

**Comment by wlannistamps** [comment]
Closed this up, thank you!
