### ISSUE TITLE
Manually set cookies domain

### ISSUE THREAD

**Issue by angelod1as** [alinemorelli/react-gtm#131]
I'm using your amazing script to initialize and send events to GTM but I'm in need of changing the cookies domain of *all* GTM tags in my app.

I see I can do it manually for each tag but, man, we have thousands.

Is there a way to do it globally via your script?

Thanks.

**Comment by daniel-bartylla** [comment]
It sounds like you need to add and take consent into account for all your tags in GTM itself. If yes, the script is unable to help you, but you could use the [GTM API](https://developers.google.com/tag-platform/tag-manager/api/v2) to automate the necessary adjustments.

But maybe I misunderstood your question. In that case, could you provide a little more information about what exactly you're trying to achieve?

**Comment by angelod1as** [comment]
Of course I can give you more detail, and if it's possible you can give me more info on how to do it via the script or GTM API.

All my cookie domains are set on "auto", which targets domain + 1 subdomain. I don't want it targeting my subdomain — it's clashing with other cookies, as I have several different services on subdomains.

As I know "www" can count as a subdomain, I want to explicitly say: target site.com and www.site.com only, ignore subdomains.

Is this enough info?

**Comment by daniel-bartylla** [comment]
A cookie set at root level (`site.com`) is automatically available for all subdomains. It's fundamental logic of how HTTP works ([RFC 6265](https://www.rfc-editor.org/rfc/rfc6265#section-5.1.4)):

> A request-path path-matches a given cookie-path if at least one of the following conditions holds:
> 
> - The cookie-path and the request-path are identical.
> - The cookie-path is a prefix of the request-path, and the last character of the cookie-path is %x2F ("/").
> - The cookie-path is a prefix of the request-path, and the first character of the request-path that is not included in the cookie- path is a %x2F ("/") character.

So this script, the mentioned API or any of the Google Tags can't change this behavior. The only advice I have is to rethink your site structure.

**Comment by angelod1as** [comment]
Thanks for the clarification.
