### ISSUE TITLE
userID not being passed

### ISSUE THREAD

**Issue by mpbunch** [alinemorelli/react-gtm#14]
I have followed the README instructions to a T, and userID is not being passed to GA.
I have tested GTM variables with default values, and those are going into the user_id view.
I added a custom dimension, and see the default value from GTM in GA.

I've removed all of the complexity of my application, and replaced it with a simple test.
```
const tagManagerArgs = {
  gtmId: 'GTM-000000',
  dataLayer: {
    userId: 'aaa-123',
    page: 'test'
  }
}
TagManager.initialize(tagManagerArgs)
```

aaa-123 never makes it to GA.

I installed GA Debug chrome extension, and userID is not found in the values returned.

Within the console, window.dataLayer returns the dataLayer variables including the userID.

So, I'm not sure which portion of this module is failing, but I can not get it to work.

**Comment by alinemorelli** [comment]
Hi mpbunch,
to better understand at what point this information is being lost, can you check two things?

1) Install the Google Tag Assistant chrome extension instead of GA Debug, make sure the userId is displayed in the extension's datalayer tab:

![export 1](https://user-images.githubusercontent.com/20077808/47582122-e1347c80-d929-11e8-96e6-030477a2d1e3.png)


2) Verify that the variable names entered in the datalayer are exactly the same as those configured in the GTM panel:

![export](https://user-images.githubusercontent.com/20077808/47581970-5ce1f980-d929-11e8-97bb-5f517180f0ec.png)

**Comment by mpbunch** [comment]
dataLayer from extension:
```
[
  {
    "gtm.start": 1540574735132,
    "event": "gtm.js",
    "gtm.uniqueEventId": 0
  },
  {
    "userId": "aaa-123"
  },
  {
    "event": "gtm.dom",
    "gtm.uniqueEventId": 2
  },
  {
    "event": "gtm.scrollDepth",
    "gtm.scrollThreshold": 10,
    "gtm.scrollUnits": "percent",
    "gtm.scrollDirection": "vertical",
    "gtm.triggers": "8127345_21,
    8127345_78,
    8127345_79,
    8127345_80,
    8127345_93,
    8127345_94,
    8127345_139",
    "gtm.uniqueEventId": 3
  },
  {
    "event": "gtm.scrollDepth",
    "gtm.scrollThreshold": 25,
    "gtm.scrollUnits": "percent",
    "gtm.scrollDirection": "vertical",
    "gtm.triggers": "8127345_21,
    8127345_78,
    8127345_79,
    8127345_80,
    8127345_93,
    8127345_94,
    8127345_139",
    "gtm.uniqueEventId": 5
  },
  {
    "event": "gtm.scrollDepth",
    "gtm.scrollThreshold": 33,
    "gtm.scrollUnits": "percent",
    "gtm.scrollDirection": "vertical",
    "gtm.triggers": "8127345_21,
    8127345_78,
    8127345_79,
    8127345_80,
    8127345_93,
    8127345_94,
    8127345_139",
    "gtm.uniqueEventId": 7
  },
  {
    "event": "gtm.load",
    "gtm.uniqueEventId": 9
  }
]
```
![screen shot 2018-10-26 at 1 27 37 pm](https://user-images.githubusercontent.com/7864344/47582875-a16a9680-d923-11e8-8d48-505f5bf02654.png)
![screen shot 2018-10-26 at 1 30 00 pm](https://user-images.githubusercontent.com/7864344/47582884-a6c7e100-d923-11e8-8587-68c60cc3aa08.png)

**Comment by alinemorelli** [comment]
I'm closing the issue because it's not a package bug. This is a problem in the configuration since to send data to the dataLayer you must ensure that it is available.
