### ISSUE TITLE
adding DataLayer.Push

### ISSUE THREAD

**Issue by yanchuk** [alinemorelli/react-gtm#17]
Hi!
Found it's not very convenient for sending events. Maybe to add built in function for that?
Just to have everything our of the box. 

```
const tagManagerArgs = {
    gtmId: 'GTM-000000',
    events: {
        sendUserInfo: 'userInfo'
    }
}
 
TagManager.initialize(tagManagerArgs)
```

initializes a GTM tag second time in case I initialized it on a page load. In case I need to send en event to DataLayer e.g. on button submit 

Thanks

**Comment by hhsadiq** [comment]
Just a question. We can also send event through dataLayer. https://developers.google.com/tag-manager/devguide#events
`dataLayer.push({'event': 'event_name'});`

Is this event somewhat different to whats initialized initially?

**Comment by benschac** [comment]
this would be awesome.

**Comment by alinemorelli** [comment]
@yanchuk

You already can use dataLayer.push to send events with this function: 
`TagManager.dataLayer({ dataLayer: { event: 'event_name' } })`

**Comment by lorenzoPenaScalablePress** [comment]
This one should be closed, right? This functionality already exists :)

**Comment by lordenzo** [comment]
This one can be closed, correct? This functionality already exists :)

**Comment by mrp97** [comment]
> This one can be closed, correct? This functionality already exists :)

It's better to document this functionality.

**Comment by n1zee** [comment]
> This one can be closed, correct? This functionality already exists :)

No!
If i use redux saga and initialize TagManager on app loads. It's initializes a GTM tag second time
If i check window.datalayer TagManager initializes a GTM tag 1 times
But if after this i try to create event like { event: 'select_content' } TagManager initializes one more GTM tag

**Comment by alinemorelli** [comment]
> > This one can be closed, correct? This functionality already exists :)
> 
> It's better to document this functionality.

It is already on Read me: https://github.com/alinemorelli/react-gtm#events

**Comment by alinemorelli** [comment]
> > This one can be closed, correct? This functionality already exists :)
> 
> No!
> If i use redux saga and initialize TagManager on app loads. It's initializes a GTM tag second time
> If i check window.datalayer TagManager initializes a GTM tag 1 times
> But if after this i try to create event like { event: 'select_content' } TagManager initializes one more GTM tag

Your problem is not related to this issue.
Please verify which version you are using, because version 2.0.6 fixed it. If you are using 2.0.6 or more please open another issue.

**Comment by amangeot** [comment]
> > > This one can be closed, correct? This functionality already exists :)
> > 
> > 
> > It's better to document this functionality.
> 
> It is already on Read me: https://github.com/alinemorelli/react-gtm#events

Hello, can you document this feature? 

I installed this module and also found it pretty hard to find info on how to send events, data, or any feature without using TagManager.initialize()

Thank you for the module

**Comment by mrp97** [comment]
> 
> 
> > > > This one can be closed, correct? This functionality already exists :)
> > > 
> > > 
> > > It's better to document this functionality.
> > 
> > 
> > It is already on Read me: https://github.com/alinemorelli/react-gtm#events
> 
> Hello, can you document this feature @alinemorelli ?
> 
> I installed this module and also found it pretty hard to find info on how to send events, data. The documentation only mentions using TagManager.initialize()
> 
> Thank you for the module

First make sure that you have installed latest version. You can install latest version by command below:
`npm i --save react-gtm-module@latest`

Then use code below for push events to Google Tag Manager.
`TagManager.dataLayer` function, works like `push` function in official GTM documentation.

`
TagManager.dataLayer({
    dataLayer: {
      'event': 'eventName',
      //other
    }
})

`

**Comment by itailulu** [comment]
This should be documented, just wasted 3 hours on it :(

**Comment by mrp97** [comment]
> This should be documented, just wasted 3 hours on it :(

Exactly. for mine 6 hours!!
