### ISSUE TITLE
Getting 404 requesting from googletagmanager.com

### ISSUE THREAD

**Issue by juanparadox** [alinemorelli/react-gtm#19]
The package is trying to call out to `https://www.googletagmanager.com/gtm.js` in order to initialize, but it returns a 404.

I tried going to `googletagmanager.com` and it does not exist.

**Comment by richardblondet** [comment]
@juanparadox it just happened to me as well. The package is calling the https://www.googletagmanager.com/gtm.js file based on the [documentation](https://developers.google.com/tag-manager/quickstart) but that url gives back a 404. Meanwhile the https://www.googletagmanager.com/gtag/js?id=UA-0000-0 works. 

@alinemorelli should you update the code? I can PR with the change

**Comment by alinemorelli** [comment]
@richardblondet  https://www.googletagmanager.com/gtag/js?id=UA-0000-0  is the tag to google analytics not for google tag manager.

@juanparadox  Can you check if you have some publish container? If it is not published, the request will return a 404 error.

**Comment by richardblondet** [comment]
Hey, you are right, thanks for the heads up

**Comment by juanparadox** [comment]
@alinemorelli I will check and get back to you, thank you

**Comment by juanparadox** [comment]
@alinemorelli There was no published container. Now that there is one, I am no longer seeing the 404. Is this the only case where a 404 would occur? If so, has there been a consideration in adding another info console to let the user know?

**Comment by alinemorelli** [comment]
If you are using a wrong GTM id it will return 404 too. I don't know any other case, but to do this kind of validation I need an extra request that will impact on application performance, I believe that the gain does not justify it. But I will add a note on readme to warning about the need of a published container.
