### ISSUE TITLE
noscript doesn't get appended to page

### ISSUE THREAD

**Issue by vire** [alinemorelli/react-gtm#2]
When I disable javascript in chrome, the bundle doesn't get executed and the `<noscript>` tag won't be appended.

I don't think it's possible to handle such scenario in this library, but I'd add maybe a notice about this fact.

**Comment by nitelite** [comment]
I guess it might work as intended with JS disabled if you are doing server-side rendering. If you are not, you are correct, there isn't much a JS lib can do on the client.

**Comment by alinemorelli** [comment]
I don't think that is possible to handle disabled javascript, but I will test it with isomorphic application to give you a better answer.

**Comment by alinemorelli** [comment]
Sorry for the delay, but I tested the library implementation on an isomorphic project and the scripts are loaded normally. But as you suggested I added a notification on read me informing about the problem with applications rendered only on the client side.
