### ISSUE TITLE
working example required

### ISSUE THREAD

**Issue by twaghmiles** [alinemorelli/react-gtm#28]
Help Wanted!

I am trying to integrate react-gtm-module in my project. I am not able to get it working on route changes.

`app.js` (where I am mounting react (`ReactDOM.render`))

```
import TagManager from 'react-gtm-module';

const tagManagerArgs = {
    gtmId: 'GTM-XXXXXX',
    dataLayer: {
        staticData: 'loan-application',
    },
};

TagManager.initialize(tagManagerArgs);
```

`component.js`
```
import TagManager from 'react-gtm-module';

const tagManagerArgs = {
  gtmId: 'GTM-NP4NM74',
  dataLayer: {
    staticData: 'loan-application',
    page: 'dashboard',
  },
};

...

componentDidMount() {
    TagManager.dataLayer(tagManagerArgs);
}
```
What I am trying to do is register a pageview when component mounts. Some of my components contain tabs which does not have it's own route.

Can anyone please provide a working example or point me in correct direction?

**Comment by SebCodesStuff** [comment]
I'm also trying to record pageviews when the component mounts. Is this possible with react gtm module?

**Comment by lordenzo** [comment]
@SebCodesStuff Did you try with:
```
componentDidMount() {
  TagManager.dataLayer(yourData);
}
```

**Comment by SebCodesStuff** [comment]
@lordenzo Yeah with that route I can fire custom events but I cant seem to get it to work for a your standard built in gtm pageview event

**Comment by lordenzo** [comment]
@SebCodesStuff I think I don't follow. :(
The `dataLayer` method is this piece of code:
```
  dataLayer: function ({dataLayer, dataLayerName = 'dataLayer'}) {
    window[dataLayerName].push(dataLayer)
  }
```

So if in the componentDidMount, you made something like:
```
componentDidMount() {
  const data = {
    event: 'PageView',
    yourData: {
      someField: 'foo',
      otherField: 'bar'
    }
  };
  TagManager.dataLayer(data);
}
```
This will push `data` into your GTM DataLayer.

**Comment by twaghmiles** [comment]
I implemented google tag manager in vanilla JavaScript. Closing issue.

**Comment by shaikabbas051** [comment]
> @SebCodesStuff I think I don't follow. 😕
> The `dataLayer` method is this piece of code:
> 
> ```
>   dataLayer: function ({dataLayer, dataLayerName = 'dataLayer'}) {
>     window[dataLayerName].push(dataLayer)
>   }
> ```
> 
> So if in the componentDidMount, you make something like:
> 
> ```
> componentDidMount() {
>   const data = {
>     event: 'PageView',
>     yourData: {
>       someField: 'foo',
>       otherField: 'bar'
>     }
>   };
>   TagManager.dataLayer(data);
> }
> ```
> 
> This will push `data` into your GTM DataLayer.

Where should I add this code?

**Comment by celest67** [comment]
I tried this on my component.js

componentDidMount () {
        const data = {
            page: '/page/error',
            event: 'vpv',
            error: '​My msg'
          };
          TagManager.dataLayer(data);
      }

and it doesn't do anything. No call to gtm, nothing.

**Comment by chunker-admin** [comment]
My experience is the react-gtm-module doesn't work when sending events.  I looked at the code in github, and the gtm snippet seems different.  I don't know what the problem with the code is, but I switched to use pure JS and it worked fine (inside my CRA).

**Comment by ozanmanav** [comment]
Hi @chunker-admin, I am also suffering from the same problem, can you help me with this?

**Comment by ozanmanav** [comment]
I guess, it's working with this code ;

TagManager. dataLayer({
    dataLayer: {
      event: "build"
    }
  })

![image](https://user-images.githubusercontent.com/19241756/75811677-e6b39980-5d9d-11ea-9d74-769ecd041002.png)

**Comment by Shihab-Github** [comment]
can you provide a full example ?

**Comment by Shihab-Github** [comment]
@ozanmanav can you provide a full example bro ?

**Comment by chunker-admin** [comment]
Simply use the plain javascript solution as outlined by Google.

https://support.google.com/tagmanager/answer/6103696?hl=en

No need for a React version.

Install your Google Tag Manager smippet in your index.html of your CRA (Create React App) in the Public folder according to the documentation.

Then, when you need to send an event, just execute the following:

window.dataLayer.push({ event: "my event" });

**Comment by AlexMachin-Xercise4Less** [comment]
@chunker-admin Always try and avoid what your suggesting, you should really fire the event in the app.js file. To initalize react-gtm-module you will need to fire the initalize event and provide your gtmId e.g. `gtm.initalize({gtmId: proccess.env.GTMID})` or if you use Azrue  `gtm.initalize({gtmId: settings.GTMID})` 

Once you have initalize google tag manager you can fire events like this example:
![image](https://user-images.githubusercontent.com/54274367/84035974-7a47c800-a994-11ea-99b7-aba17bc302d0.png)

**NOTE:**

For accurate page views just create a custom event and pass the data yourself ie title, url and search params. This can be done in your apps head, if your using react-helmet you can use the onChangeClientState HELMET prop to fire the event.

It will fire twice so you need to keep track of if the event has been fired or not.

**Comment by BenHunt-io** [comment]
I got the TagManager.dataLayer(...) to fire when I did not supply a dataLayerName. Maybe this is because I didn't define that in the TagManager.init? 

Just sharing what I found worked.

**Comment by AlexMachin-Xercise4Less** [comment]
@BenHunt-io Honestly we ditched this plugin, instead at work we kept having issues with it. So we used our  approach with snippets provided from the GTM docs.

**Comment by melmichael-cs** [comment]
Thanks, @chunker-admin. I followed your approach and it worked for me.

For others, the following may help in setting it up. 


## 1.  Initialize your arguments including the events
// App.js 
```js
const tagManagerArgs = {
  gtmId: process.env.REACT_APP_GTM_ID,
  events: {
    logIn: 'Log In',
    signUp: 'Sign Up',
  }
}

TagManager.initialize(tagManagerArgs);
```

## 2. Call the datalayer function inside where you need it to fire.

 ```js
TagManager.dataLayer({
    dataLayer: {
        event: 'logIn', // event name declared during initialization
        userId: email,
       // add more data you want here
    }
});
```

## 3. Use the defined events name on the app in defining a 'Trigger' on GTM

![Screen Shot 2020-09-22 at 10 48 17 AM](https://user-images.githubusercontent.com/66741595/93867676-4bdec600-fcc1-11ea-9f88-efd6d4aaf879.png)


## 4. Repeat same for the Tag definition


![Screen Shot 2020-09-22 at 10 48 48 AM](https://user-images.githubusercontent.com/66741595/93867884-92342500-fcc1-11ea-96d9-22ed2881925e.png)



**Note: The Category name was added to help GA organise the different events you want to capture. You can call it any name. No need to add it in your code or GA.**

**Comment by qnxdev** [comment]
It was adblocker that caused issue for me 

https://github.com/alinemorelli/react-gtm/issues/72#issuecomment-917129811
