### ISSUE TITLE
TypeError: window[dataLayerName] is undefined

### ISSUE THREAD

**Issue by eplouhinec** [alinemorelli/react-gtm#30]
Hello,

Same as what been said here : https://github.com/alinemorelli/react-gtm/commit/753c01acf7981d68c83aa055b1fd518161a3f950#commitcomment-33917679

... a call to `TagManager.dataLayer(..., layerName)` give an error "TypeError: window[dataLayerName] is undefined" even if `initialize()` method have been called before. Seems that this two methods manipulate datas from two different memory areas.

**Comment by brnmonteiro** [comment]
same here

**Comment by alinemorelli** [comment]
Fixed on #37
