### ISSUE TITLE
dataLayer inserted after GTM script

### ISSUE THREAD

**Issue by estojav** [alinemorelli/react-gtm#38]
Noticed that dataLayer is inserted after GTM script, according to the official docs https://developers.google.com/tag-manager/devguide, there is a note "If you put the Google Tag Manager container snippet above the dataLayer array, Google Tag Manager may malfunction, and will not be able to read the variables defined in the array."

**Comment by alinemorelli** [comment]
Fixed on  [version 2.0.9](#65)

**Comment by ianninirojas** [comment]
Hi, I think this is happening again, the dataLayer is inserted after  GTM script
