### ISSUE TITLE
Jquery is not defined

### ISSUE THREAD

**Issue by TizioFittizio** [alinemorelli/react-gtm#39]
Hello, i wrote an hidden component in order to initialize the package:

```ts
import * as React from 'react';
import TagManager from 'react-gtm-module'

interface Props { }

interface State { }

class GoogleTagManager extends React.Component<Props, State> {

    private static TAG_MANAGER_ARGS = {
        gtmId: 'GTM-XXXXXXX'
    };

    constructor(props: Props){
        super(props);
        TagManager.initialize(GoogleTagManager.TAG_MANAGER_ARGS)
    }

    render() {
        return null;
    }

}

export default GoogleTagManager;
```

Then, this is simply rendered to trigger the initialization in the constructor:
```tsx
<GoogleTagManager />
```

But this error is printed after some seconds:
```
VM43:1 Uncaught ReferenceError: jQuery is not defined
    at <anonymous>:1:1
    at gtm.js?id=GTM-XXXXXXX&gtm_auth=&gtm_preview=&gtm_cookies_win=x:942
    at gtm.js?id=GTM-XXXXXXX&gtm_auth=&gtm_preview=&gtm_cookies_win=x:943
    at gtm.js?id=GTM-XXXXXXX&gtm_auth=&gtm_preview=&gtm_cookies_win=x:943
    at Object.c [as __html] (gtm.js?id=GTM-XXXXXXX&gtm_auth=&gtm_preview=&gtm_cookies_win=x:944)
    at tb (gtm.js?id=GTM-XXXXXXX&gtm_auth=&gtm_preview=&gtm_cookies_win=x:790)
    at e (gtm.js?id=GTM-XXXXXXX&gtm_auth=&gtm_preview=&gtm_cookies_win=x:817)
    at gtm.js?id=GTM-XXXXXXX&gtm_auth=&gtm_preview=&gtm_cookies_win=x:782
    at Array.<anonymous> (gtm.js?id=GTM-XXXXXXX&gtm_auth=&gtm_preview=&gtm_cookies_win=x:818)
    at Object.Qf (gtm.js?id=GTM-XXXXXXX&gtm_auth=&gtm_preview=&gtm_cookies_win=x:817)
```

Without the component, no error is throw
I'm using `2.0.8` version

**Comment by TizioFittizio** [comment]
Sorry the code tag manager was executing was using jquery

**Comment by fahmi-pdso** [comment]
so how do you manage to resolve this issue? apparently I stumble upon the same one

**Comment by TizioFittizio** [comment]
Hello, basically (if I recall correctly, this was 4 years ago lol) the component above works fine, however, the code that was injected by the tag manager was calling jquery functions which usually you don't have in a react project. Some solutions that comes to mind:
1. Modify your tag manager injected code to not rely on jquery (it may be hard if you are just using third party stuff)
2. Install jquery in your project and have it callable globally

**Comment by fahmi-pdso** [comment]
Hello @TizioFittizio, thank you for answering. I learn a lot of stuff since then 👍
