### ISSUE TITLE
Is it a React only solution?

### ISSUE THREAD

**Issue by Sergeyshall** [alinemorelli/react-gtm#40]
I don't see any React dependency in code. Seems like this library is legit for any JS app (even those not React based), am I right?

**Comment by bailer** [comment]
Yeah I had the same concern. What about this package is react specific?

**Comment by 8brandon** [comment]
yea, it's being imported in the snippet.spec test, but not being used..

**Comment by alinemorelli** [comment]
At first time the lib was developed based on react components, but now it is not using react. So I'm removing react from dependencies and from snippet.spec on [version 2.0.10](#66 )

**Probably you can use it on any JS app**, but right now I can't test it.

As soon as possible I will test it, and if it works fine I can publish a new package where I can support other implementations.
