### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by smithaitufe** [alinemorelli/react-gtm#42]
Hi,

Can someone give a clear tutorial of how to use this package with google tag manager in ReactJS?

Basic steps to follow will be great.

From my observation, using this component does not work but when I insert the tag manager script manually in the index.html, tag manager works.

Perhaps I am missing the basic initialization process.

**Comment by lordenzo** [comment]
@smithaitufe Hi there! Do you mind telling me where are you stuck? All the initialization and usage of the component are in the readme of the repo, maybe it could be improve, but we will need to know what are the parts that are not clear.

**Comment by smithaitufe** [comment]
@lordenzo So this was what I did.

After installing package, I wrote the codes below.

```
const tagManagerArgs = {
            gtmId: config.GOOGLE_TAG_MANAGER_ID
        }
        TagManager.initialize(tagManagerArgs);
```
Thereafter, I created a component that monitors changes in location and sends information of the page through `dataLayer`.

```
const page = pathname + search
    const { location } = window
    TagManager.dataLayer({
        dataLayer: {
            page: `${location.origin}${page}`,
        },
        dataLayerName: "Page",
    })
```

That is all I did.

**Comment by lordenzo** [comment]
@smithaitufe That looks correct. Please make sure that the `initialize` part is in your `root/main.[js|ts]`, wherever you are defining the `ReactDOM.render` of your app.
The second part should go in whatever page/component you want the data to be pushed to the dataLayer.

**Comment by smithaitufe** [comment]
@lordenzo That is the way it is actually.
Do I need to include any reference in the index.html?

**Comment by smithaitufe** [comment]
@lordenzo Keep this in mind

https://github.com/alinemorelli/react-gtm/issues/28

**Comment by nykanenj** [comment]
I had problems getting this working. I was using the tag manager script and this module as the website has static and react pages:


<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-XXXXXX');</script>


However, adding this script with the module caused the module-side code not to work. Removing the above tag manager script and only using this react-gtm-module worked for me.

**Comment by alinemorelli** [comment]
As it has not had recent activity, I will close this issue, if you still having problem to implement let me know.
