### ISSUE TITLE
remove `gtm_preview` if not in preview mode

### ISSUE THREAD

**Issue by RobertHeim** [alinemorelli/react-gtm#48]
In GTM we can select to only trigger an event in live environment. However, using react-gtm, this event would NOT fire in live environment - I think maybe because react-gtm always adds the `gtm_preview` parameter?

https://github.com/alinemorelli/react-gtm/blob/52f2328ab1b45734c342e9021fe693795a03972d/src/Snippets.js#L8

Maybe we can check the paramter for being empty and and if so obmit the param:
```
const gtm_preview = !preview ? '' : `&gtm_preview=${preview}`
```

**Comment by mos-adebayo** [comment]
These are valid fix and need to be merged. **gtm_auth** and **gtm_preview** are optional and should not be added to the URL when they are not set
