### ISSUE TITLE
Append script/noscript as first child

### ISSUE THREAD

**Issue by thaithcock** [alinemorelli/react-gtm#5]
Google has in their documentation that their `script` should be as close to the top of the `head` tag  and the `noscript` should be the first thing in the `body` tag.

It is just being appended, so if there were any pre-existing elements this would append them in non-ideal locations. It would be good to be a little bit more defensive about making sure it is appending it as the first element in head/body. If something comes in later and inserts as first there is nothing you can do, but it should not stop this library from doing things as best it can.

There's various ways to accomplish this. [Here's a SO link](https://stackoverflow.com/questions/2007357/how-to-set-dom-element-as-the-first-child) for setting elements as the first child.

**Comment by david-soyez** [comment]
do you mean it should use an insertBefore on the first index element of header and body?
https://github.com/alinemorelli/react-gtm/blob/master/src/TagManager.js#L42

**Comment by thaithco** [comment]
Yes, basically just replace those two `appendChild` calls.

**Comment by nikopavlica** [comment]
Isn't `noscript` basically useless since its never going to trigger, because if user has javascript disabled react won't even run?

If this module would support server-side rendering, then it would be useful.

**Comment by alinemorelli** [comment]
Thank you for the report, fixed in the version 2.0.4.
