### ISSUE TITLE
GTM with Next Js

### ISSUE THREAD

**Issue by kkashou** [alinemorelli/react-gtm#56]
Hello,

I am having trouble implementing react-gtm to my nextJs project.

I have a _app.jsx file that has this example

```
import React from 'react'
import NextApp from 'next/app'
import { ThemeProvider } from 'emotion-theming'
import theme from '@styles/theme'
import TagManager from 'react-gtm'

 const tagManagerArgs = {
   id: 'GTM-XXXXXX'
 }
 export default class App extends NextApp {
   componentDidMount() {
     TagManager.initialize(tagManagerArgs)
   }

   render() {
     const { Component, pageProps } = this.props

     return (
       <ThemeProvider theme={theme}>
         <Component {...pageProps} />
       </ThemeProvider>
     )
   }
 }
```

I am still not getting any thing show up on my page that GTM is on the site.

Any help would be appreciated.

**Comment by shakesBeardZ** [comment]
I don't think this package will you, check this link and try to implement it the same way 
https://github.com/zeit/next.js/tree/canary/examples/with-google-analytics

**Comment by kkashou** [comment]
@shakesBeardZ  - So basically change the ga code to work with GTM code but I don't think that GTM has the abiliity to do the page view like ga did in the lib https://github.com/zeit/next.js/blob/canary/examples/with-google-analytics/lib/gtag.js

You see what I mean?

**Comment by shakesBeardZ** [comment]
@kkashou 
I successed in adding GTM to my nextjs app by inspiring from the example I gave u.
simply add your GTM code in the <Head> tag in _document.js

```
         <script
              dangerouslySetInnerHTML={{
                __html: `
                (function(w, d, s, l, i){
                  w[l] = w[l] || []; w[l].push({
                      'gtm.start':
                          new Date().getTime(), event: 'gtm.js'
                  }); var f = d.getElementsByTagName(s)[0],
                      j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                          'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
                }) (window, document, 'script', 'dataLayer', 'GTM-ID');
            `,
              }}
          />
``` 
![image](https://user-images.githubusercontent.com/15571628/77629161-22372300-6f5a-11ea-94dd-983ba78b66a2.png)

**Comment by kkashou** [comment]
@shakesBeardZ - I see but there’s another thing that needs to be added after the opening body tag and in that example you provided they have ways to track each page when you move to a new route. Do I have to still do that part?

**Comment by kylemh** [comment]
@kkashou one thing is that you have `id` instead of `gtmId` in your `tagManagerArgs`

**Comment by shakesBeardZ** [comment]
@kkashou I'm not doing that and it's working fine for me

**Comment by kkashou** [comment]
@shakesBeardZ  thanks!
