### ISSUE TITLE
Getting 404 in gtag.js

### ISSUE THREAD

**Issue by samueldervis** [alinemorelli/react-gtm#59]
I am getting a 404 error in the js included by this package
![image](https://user-images.githubusercontent.com/25820084/80228104-48360d00-8657-11ea-8bb1-d820b253a0fd.png)

**Comment by herel** [comment]
@samueldervis 
I was just doing the same thing about 1 hour ago.

You must send the version to be published on the google tag manager page

![Captura de Pantalla 2020-04-24 a la(s) 13 00 36](https://user-images.githubusercontent.com/416115/80242816-9b926600-862b-11ea-9478-b390dff01ad8.png)

**Comment by samueldervis** [comment]
Thanks
