### ISSUE TITLE
Environment Support

### ISSUE THREAD

**Issue by joaofranca** [alinemorelli/react-gtm#6]
Is it possible to [configure different envs](https://support.google.com/tagmanager/answer/6311518?hl=en)? 

As far as I see, the difference is in a parameter called _gtm_preview_ in the snippet that points to the desired env.

**Comment by Vadorequest** [comment]
@alinemorelli I saw you assigned this task to yourself, I made a fork of your repo and added this feature a few hours ago, alongside other changes (including the HTTPS)

Feel free to use it: https://github.com/Vadorequest/react-gtm

**Comment by alinemorelli** [comment]
#9 
@joaofranca added on v2.0.0. Thanks for your suggestion.

@Vadorequest When I saw your message it is already done, but I will see your changes. Thank you.
